sudo: required
services:
    - docker

before_install:
    - docker build -t tariqbeans/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tariqbeans/react-test npm test npm test

after_sucess:
    - docker build -t tariqbeans/multi-client ./client
    - docker build -t tariqbeans/multi-nginx ./nginx
    - docker build -t tariqbeans/multi-server ./server
    - docker build -t tariqbeans/multi-worker ./worker
    # lon in to the docker CLI
    - echo "$DOCKER_PASSWORD"  |docker login -u "$DOCKER_ID" --password-stdin 
    # take those images and push them to docker hub
    - docker push tariqbeans/multi-client  
    - docker push tariqbeans/multi-nginx  
    - docker push tariqbeans/multi-server  
    - docker push tariqbeans/multi-worker

    deploy:
        provider: elasticbeanstalk
        region: eu-west-3
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-eu-west-3-066550581276
        bucket_path: docker-multi
    on:
        branch: master
        
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
